name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - 'java8/**'
      - '.github/workflows/maven.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'java8/**'
      - '.github/workflows/maven.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
      - name: Run Maven verify
        working-directory: ./java8
        run: mvn --batch-mode verify